spring.application.name=mail-template-ivlin
server.port=8082

# SMTP settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=samvjaathish@gmail.com
spring.mail.password=impf txja dxpx udjy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true